# Usa una imagen base de Nginx
FROM nginx:alpine

# Copia los archivos estáticos al directorio de Nginx
COPY public /usr/share/nginx/html

# Expone el puerto utilizado por Nginx
EXPOSE 80

# Nginx se ejecutará automáticamente como proceso principal