version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - static

  static:
    build:
      context: .
      dockerfile: Dockerfile.static
    ports:
      - "80:80"
