version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true" # Expone este contenedor a Traefik
      # Router para HTTPS
      - "traefik.http.routers.app-secure.rule=Host(`n1rocket.com`)"
      - "traefik.http.routers.app-secure.entrypoints=websecure"
      - "traefik.http.routers.app-secure.tls=true"
      - "traefik.http.routers.app-secure.tls.certresolver=myresolver"
      # Router para HTTP que redirige a HTTPS
      - "traefik.http.routers.app-insecure.rule=Host(`n1rocket.com`)"
      - "traefik.http.routers.app-insecure.entrypoints=web"
      - "traefik.http.routers.app-insecure.middlewares=redirect-to-https"
      # Middleware para redirección
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # Puerto del servicio interno
      - "traefik.http.services.app.loadbalancer.server.port=8080"
    networks:
      - web

networks:
  web:
    external: true
