version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      VIRTUAL_HOST: n1rocket.com
      LETSENCRYPT_HOST: n1rocket.com
      LETSENCRYPT_EMAIL: n1rocketdev@gmail.com
    networks:
      - web

  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - web

  docker-gen:
    image: nginxproxy/docker-gen
    command: >
      sh -c " curl -o /etc/docker-gen/templates/nginx.tmpl https://raw.githubusercontent.com/nginx-proxy/docker-gen/master/templates/nginx.tmpl && /usr/local/bin/docker-gen -notify-sighup nginx-proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - nginx-proxy
    networks:
      - web
    labels:
      com.github.nginx-proxy.docker-gen: "true"

  letsencrypt:
    image: nginxproxy/acme-companion
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
      NGINX_DOCKER_GEN_CONTAINER: docker-gen
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - nginx-proxy
      - docker-gen
    networks:
      - web

networks:
  web:
