apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-helm
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.letsencrypt.email }}
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
      - dns01:
          webhook:
            groupName: {{ .Values.letsencrypt.ovh.groupName }}
            solverName: ovh
            config:
              endpoint: ovh-eu
              applicationKey: {{ .Values.letsencrypt.ovh.applicationKey }}
              applicationSecretRef:
                key: applicationSecret
                name: ovh-credentials
              consumerKey: {{ .Values.letsencrypt.ovh.consumerKey }}
